export const GET_ADVERTS_START = 'GET_ADVERTS_START'
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS'
export const GET_ADVERTS_FAILURE = 'GET_ADVERTS_FAILURE'

export const LOAD_MORE_START = 'LOAD_MORE_START'
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS'
export const LOAD_MORE_FAILURE = 'LOAD_MORE_FAILURE'

export const GET_ADVERT_BY_ID_START = 'GET_ADVERT_BY_ID_START'
export const GET_ADVERT_BY_ID_SUCCESS = 'GET_ADVERT_BY_ID_SUCCESS'
export const GET_ADVERT_BY_ID_FAILURE = 'GET_ADVERT_BY_ID_FAILURE'