export const GET_ADVERTS_START = 'GET_ADVERTS_START'
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS'
export const GET_ADVERTS_FAILURE = 'GET_ADVERTS_FAILURE'

export const LOAD_MORE_START = 'LOAD_MORE_START'
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS'
export const LOAD_MORE_FAILURE = 'LOAD_MORE_FAILURE'

export const GET_ADVERT_BY_ID_START = 'GET_ADVERT_BY_ID_START'
export const GET_ADVERT_BY_ID_SUCCESS = 'GET_ADVERT_BY_ID_SUCCESS'
export const GET_ADVERT_BY_ID_FAILURE = 'GET_ADVERT_BY_ID_FAILURE'

export const SEARCH_ADVERT = 'SEARCH_ADVERT'

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const REGISTRATION_START = 'REGISTRATION_START'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
